apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: impiger-user-service
  description: User management microservice for Impiger platform

  annotations:
    github.com/project-slug: YOUR_GITHUB_USERNAME/impiger-user-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: impiger-user-service
    jenkins.io/job-full-name: impiger-user-servic

spec:
  type: service
  lifecycle: production
  owner: group:default/platform-engineering
  system: impiger-platform
