apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: impiger-user-service
  description: User management microservice for Impiger Technologies

  annotations:
    github.com/project-slug: KaranPrince/impiger-user-service
    jenkins.io/job-full-name: impiger-user-service

spec:
  type: service
  lifecycle: production
  owner: group:default/platform-engineering
  system: impiger-platform
